import type { Metadata } from "next";
import { Silkscreen } from "next/font/google";
import "./globals.css";

const silkscreenSans = Silkscreen({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--silkscreen-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-screen w-full bg-bg">
      <body className={`${silkscreenSans.variable}  antialiased h-screen w-screen bg-bg`}>
        {children}
      </body>
    </html>
  );
}
